# Generated by Django 5.2.14 on 2026-05-18 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("doble", "Doble"),
                            ("suite", "Suite"),
                            ("familiar", "Familiar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField()),
                ("floor", models.PositiveSmallIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="properties.accommodation",
                    ),
                ),
            ],
            options={
                "verbose_name": "habitación",
                "verbose_name_plural": "habitaciones",
                "ordering": ("floor", "number"),
                "unique_together": {("accommodation", "number")},
            },
        ),
        migrations.CreateModel(
            name="SeasonRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("baja", "Temporada baja"),
                            ("normal", "Temporada normal"),
                            ("alta", "Temporada alta"),
                            ("feriado", "Feriado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarifa por temporada",
                "verbose_name_plural": "tarifas por temporada",
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="RoomAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reserva", "Reserva"),
                            ("bloqueo", "Bloqueo manual"),
                            ("mantenimiento", "Mantenimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidad",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilidad",
                "verbose_name_plural": "disponibilidades",
                "ordering": ("date",),
                "unique_together": {("room", "date")},
            },
        ),
    ]
