# Generated by Django 5.2.14 on 2026-05-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="habitaciones/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto de habitación",
                "verbose_name_plural": "fotos de habitación",
                "ordering": ("order", "id"),
            },
        ),
    ]
