# Generated by Django 5.2.15 on 2026-07-14 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nombre comercial')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='descripción')),
                ('location', models.CharField(blank=True, help_text='Ej. Miraflores, Lima', max_length=200, verbose_name='ubicación principal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='empresas/portadas/')),
                ('ruc', models.CharField(blank=True, db_index=True, max_length=11)),
                ('legal_name', models.CharField(blank=True, max_length=250, verbose_name='razón social (SUNAT)')),
                ('is_verified', models.BooleanField(default=False, help_text='Verificación vía RUC / SUNAT.', verbose_name='empresa verificada')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Si es True, la página es visible públicamente (con o sin badge).', verbose_name='publicada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('titular', 'Titular'), ('org_manager', 'Gestor de organización'), ('local_manager', 'Gestor de local')], default='titular', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía de organización',
                'verbose_name_plural': 'membresías de organización',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uniq_org_membership_user')],
            },
        ),
    ]
