# Generated by Django 5.2.14 on 2026-05-19 14:16

from django.db import migrations, models


def approve_existing_owners(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="propietario", owner_status="").update(
        owner_status="aprobado"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_rejection_reason',
            field=models.TextField(blank=True, verbose_name='motivo de rechazo (propietario)'),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_status',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='', max_length=20),
        ),
        migrations.RunPython(approve_existing_owners, migrations.RunPython.noop),
    ]
