# Generated by Django 5.2.15 on 2026-07-27 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_identity_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_soft_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es True, la cuenta no puede iniciar sesión ni aparecer en listados públicos.', verbose_name='eliminado (soft delete)'),
        ),
    ]
