# Generated by Django 5.2.14 on 2026-05-18 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del ícono (ej. wifi)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("hostal", "Hostal"),
                            ("hospedaje", "Hospedaje"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de aprobación"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(default="Perú", max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=3
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedajes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, related_name="hospedajes", to="properties.service"
                    ),
                ),
            ],
            options={
                "verbose_name": "hospedaje",
                "verbose_name_plural": "hospedajes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AccommodationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="hospedajes/")),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="properties.accommodation",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto de hospedaje",
                "verbose_name_plural": "fotos de hospedaje",
                "ordering": ("order", "id"),
            },
        ),
    ]
