# Generated by Django 5.2.14 on 2026-05-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo si el administrador rechaza el registro (HU-10).",
            ),
        ),
    ]
