# Generated by Django 5.2.14 on 2026-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_accommodation_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('tipo', 'Tipo de alojamiento'), ('region', 'Región natural')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=80)),
                ('filter_value', models.CharField(help_text='Valor de filtro API: tipo (hotel, hostal…) o zona (costa, sierra, selva).', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inicio/')),
                ('gradient_css', models.CharField(blank=True, default='linear-gradient(135deg, #0d6e6e 0%, #4db6ac 100%)', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bloque de inicio',
                'verbose_name_plural': 'bloques de inicio',
                'ordering': ('group', 'order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('group', 'slug'), name='unique_browse_tile_group_slug')],
            },
        ),
    ]
