# Generated by Django 5.2.14 on 2026-05-22 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_accommodation_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (1–80).', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveSmallIntegerField(help_text='Duración en días naturales (incluye el día de inicio).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('end_date', models.DateField(editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivada, no aplica aunque esté en el rango de fechas.')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='properties.accommodation')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ('-start_date', '-created_at'),
            },
        ),
    ]
