# Generated by Django 5.2.14 on 2026-05-22 17:33

from django.db import migrations, models


def assign_all_rooms_to_existing_offers(apps, schema_editor):
    AccommodationOffer = apps.get_model("properties", "AccommodationOffer")
    Room = apps.get_model("rooms", "Room")
    for offer in AccommodationOffer.objects.all():
        room_ids = Room.objects.filter(
            accommodation_id=offer.accommodation_id,
            is_active=True,
        ).values_list("id", flat=True)
        if room_ids:
            offer.rooms.set(room_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_accommodationoffer'),
        ('rooms', '0002_roomphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationoffer',
            name='rooms',
            field=models.ManyToManyField(blank=True, help_text='Habitaciones incluidas en la promoción.', related_name='ofertas', to='rooms.room'),
        ),
        migrations.RunPython(
            assign_all_rooms_to_existing_offers,
            migrations.RunPython.noop,
        ),
    ]
