# Generated by Django 5.2.15 on 2026-07-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_accommodation_cancel_refund_deadlines'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='browsetileclick',
            new_name='properties__tile_id_467467_idx',
            old_name='properties__tile_id_8a4f2d_idx',
        ),
        migrations.AddField(
            model_name='browsetile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para relacionar hospedajes cercanos (lugares turísticos).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='browsetile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('hostal', 'Hostal'), ('hospedaje', 'Hospedaje'), ('casa_departamento', 'Casa o departamento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='browsetile',
            name='filter_value',
            field=models.CharField(help_text='Filtro API: tipo (hotel…), zona (costa…), departamento (Lima) o slug del lugar turístico.', max_length=80),
        ),
        migrations.AlterField(
            model_name='browsetile',
            name='group',
            field=models.CharField(choices=[('tipo', 'Tipo de alojamiento'), ('region', 'Región natural'), ('departamento', 'Departamento'), ('lugar_turistico', 'Lugar turístico')], db_index=True, max_length=20),
        ),
    ]
