# Generated by Django 5.2.15 on 2026-07-27 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_seed_tourist_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations_soft_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
    ]
