# Generated by Django 5.2.15 on 2026-07-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationoffer',
            name='event_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Si la oferta responde a un evento externo (Actify).', null=True, verbose_name='ID evento Actify'),
        ),
        migrations.AddField(
            model_name='accommodationoffer',
            name='event_name',
            field=models.CharField(blank=True, help_text='Denormalizado para mostrar en ficha sin consultar Actify.', max_length=200, verbose_name='nombre del evento'),
        ),
        migrations.AddIndex(
            model_name='accommodationoffer',
            index=models.Index(fields=['accommodation', 'event_id'], name='properties__accommo_755781_idx'),
        ),
    ]
