# Generated by Django 5.2.14 on 2026-05-21 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('ofensivo', 'Contenido ofensivo'), ('acoso', 'Acoso o amenazas'), ('spam', 'Spam o publicidad'), ('estafa', 'Estafa o engaño'), ('otro', 'Otro')], max_length=20)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('descartado', 'Descartado')], db_index=True, default='pendiente', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, max_length=500)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte de mensaje',
                'verbose_name_plural': 'reportes de mensajes',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('message', 'reporter'), name='messaging_unique_report_per_user')],
            },
        ),
    ]
