# Generated by Django 5.2.14 on 2026-05-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, db_index=True, max_length=20)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['-created_at', 'action'], name='audit_audit_created_05df2a_idx'), models.Index(fields=['actor_role', '-created_at'], name='audit_audit_actor_r_4ef892_idx')],
            },
        ),
    ]
