# Generated by Django 5.2.14 on 2026-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
