# Generated by Django 5.2.14 on 2026-05-18 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "status", "check_in", "check_out"],
                name="bookings_bo_room_id_3cac22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["guest", "status"], name="bookings_bo_guest_i_261eaf_idx"
            ),
        ),
    ]
